# Generated by Django 5.1.3 on 2024-11-20 01:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField()),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'apilog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('blurb', models.TextField()),
                ('atk', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('magic', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('load_img', models.URLField()),
                ('spar_img', models.URLField()),
                ('bbox_img', models.URLField()),
                ('tag_1', models.CharField(blank=True, max_length=50)),
                ('tag_2', models.CharField(blank=True, max_length=50)),
                ('partype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'champion',
                'managed': True,
            },
        ),
    ]
